name: lifelog_reference
description: "Reference implementation for the Lifelog Flutter learning project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  sqlite3: ^2.4.0
  path_provider: ^2.1.2
  uuid: ^4.5.2
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  widgetbook: ^3.10.0

flutter:
  uses-material-design: true
